# -*- coding: utf-8 -*-
"""Copy of fcc_predict_health_costs_with_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKBbsJdTydwboWA_FSQqH26w--OgzhHN

*Note: You are currently reading this using Google Colaboratory which is a cloud-hosted version of Jupyter Notebook. This is a document containing both text cells for documentation and runnable code cells. If you are unfamiliar with Jupyter Notebook, watch this 3-minute introduction before starting this challenge: https://www.youtube.com/watch?v=inN8seMm7UI*

---

In this challenge, you will predict healthcare costs using a regression algorithm.

You are given a dataset that contains information about different people including their healthcare costs. Use the data to predict healthcare costs based on new data.

The first two cells of this notebook import libraries and the data.

Make sure to convert categorical data to numbers. Use 80% of the data as the `train_dataset` and 20% of the data as the `test_dataset`.

`pop` off the "expenses" column from these datasets to create new datasets called `train_labels` and `test_labels`. Use these labels when training your model.

Create a model and train it with the `train_dataset`. Run the final cell in this notebook to check your model. The final cell will use the unseen `test_dataset` to check how well the model generalizes.

To pass the challenge, `model.evaluate` must return a Mean Absolute Error of under 3500. This means it predicts health care costs correctly within $3500.

The final cell will also predict expenses using the `test_dataset` and graph the results.
"""

# Commented out IPython magic to ensure Python compatibility.
# Import libraries. You may or may not use all of these.
!pip install -q git+https://github.com/tensorflow/docs
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

try:
  # %tensorflow_version only exists in Colab.
#   %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

# Import data
!wget https://cdn.freecodecamp.org/project-data/health-costs/insurance.csv
dataset = pd.read_csv('insurance.csv')
dataset.tail()

import missingno as msno
msno.matrix(dataset)


dataset.sex = pd.Categorical(dataset.sex)
dataset['sex_category'] = dataset.sex.cat.codes
dataset.smoker = pd.Categorical(dataset.smoker)
dataset['smoker_category'] = dataset.smoker.cat.codes
dataset.region = pd.Categorical(dataset.region)
dataset['region_category'] = dataset.region.cat.codes

# For normalization
# from sklearn.preprocessing import minmax_scale
# dataset[['age','bmi','expenses','children']] = minmax_scale(dataset[['age','bmi','expenses','children']])

dataset.tail()
# print(dataset['age'].value_counts())
# print(dataset['sex'].value_counts())
# print(dataset['bmi'].value_counts())
# print(dataset['children'].value_counts())
# print(dataset['smoker'].value_counts())
# print(dataset['region'].value_counts())
# print(dataset['expenses'].value_counts())

# import seaborn as sns
# sns.heatmap(dataset.isnull(), cbar=False)
x = dataset[['age', 'sex_category', 'bmi','children', 'smoker_category','region_category']]
y = dataset['expenses']
from sklearn.model_selection import train_test_split
train_dataset, test_dataset, train_labels, test_labels = train_test_split(x, y, test_size = 0.2)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(6)) #First hidden layer
model.add(tf.keras.layers.Dense(12)) #Second hidden layer
model.add(tf.keras.layers.Dropout(.2))
model.add(tf.keras.layers.Dense(1)) #Output layer

model.compile(
    optimizer=tf.optimizers.Adam(learning_rate=0.1),
    loss='mae',
    metrics=['mae', 'mse'])
model.fit(train_dataset,train_labels, batch_size=32,epochs=100)
model.summary()

# RUN THIS CELL TO TEST YOUR MODEL. DO NOT MODIFY CONTENTS.
# Test model by checking how well the model generalizes using the test set.
loss, mae, mse = model.evaluate(test_dataset, test_labels, verbose=2)

print("Testing set Mean Abs Error: {:5.2f} expenses".format(mae))

if mae < 3500:
  print("You passed the challenge. Great job!")
else:
  print("The Mean Abs Error must be less than 3500. Keep trying.")

# Plot predictions.
test_predictions = model.predict(test_dataset).flatten()

a = plt.axes(aspect='equal')
plt.scatter(test_labels, test_predictions)
plt.xlabel('True values (expenses)')
plt.ylabel('Predictions (expenses)')
lims = [0, 50000]
plt.xlim(lims)
plt.ylim(lims)
_ = plt.plot(lims,lims)